spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ggozlo

  data:
    web:
      pageable:
        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug
  ggozlo.bbsCommunity: debug




