GET http://localhost:8080/member/1

###
POST http://localhost:8080/member/join
Content-Type: application/x-www-form-urlencoded

username=test&password=aa1133&email=test@naver.com&nickname=testMember

###

POST http://localhost:8080/member/edit/username/1
Content-Type: application/x-www-form-urlencoded

newUsername=change

###


